import argparse
import csv
import json
import math
import os
import random
import time
from collections import Counter
from datetime import datetime
from typing import Dict, Iterable, List, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train iBank RiskBrain GraphSAGE edge classifier.")
    parser.add_argument("--data-dir", required=True, help="Directory containing nodes.csv, edges.csv, labels.csv.")
    parser.add_argument("--output-dir", required=True, help="Directory for metrics and model checkpoint.")
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--hidden-dim", type=int, default=128)
    parser.add_argument("--batch-size", type=int, default=8192)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--dropout", type=float, default=0.20)
    parser.add_argument("--seed", type=int, default=20260529)
    parser.add_argument("--max-edges", type=int, default=0, help="Optional edge cap for quick smoke tests.")
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--feature-mode", choices=["v1", "v2", "v3", "temporal_v1"], default="v1",
                        help="v1 keeps the original baseline features. v2 adds leakage-safe graph features "
                             "and review-feedback weights when edge_features_v2.csv exists. v3 uses only "
                             "label-free historical features computed from past transactions. temporal_v1 reads "
                             "prefix-only temporal graph features exported by build_temporal_edge_features.py.")
    parser.add_argument("--temporal-feature-file", default=None,
                        help="Required for --feature-mode temporal_v1. Path to temporal_edge_features.csv.")
    parser.add_argument("--feedback-mode", choices=["off", "weight", "label"], default="label",
                        help="label preserves older V2 behavior. Use off for leakage-safe backtests.")
    parser.add_argument("--split-mode", choices=["stratified", "time"], default="stratified",
                        help="time split evaluates on later transactions and is preferred for leakage-safe AML tests.")
    parser.add_argument("--split-file", default=None,
                        help="Optional split_indices.csv generated by build_temporal_splits.py. "
                             "When set, model_index assignments in this file override split-mode.")
    parser.add_argument("--standardize-scope", choices=["full", "train"], default="full",
                        help="train fits feature normalization on train edges only.")
    parser.add_argument("--adjacency-scope", choices=["full", "train"], default="full",
                        help="train builds message-passing adjacency from train edges only.")
    parser.add_argument("--architecture", choices=["graphsage", "directed-edge-sage"], default="graphsage",
                        help="graphsage is the V1/V2 undirected baseline. directed-edge-sage is the V3 "
                             "directed encoder with separate inbound/outbound aggregation and edge updates.")
    parser.add_argument("--loss", choices=["bce", "focal"], default="bce")
    parser.add_argument("--focal-gamma", type=float, default=2.0)
    parser.add_argument("--hard-negative-ratio", type=float, default=0.0,
                        help="After warmup, upweight the top-k hardest negative train edges. "
                             "k = positives * hard_negative_ratio.")
    parser.add_argument("--hard-negative-weight", type=float, default=2.0)
    parser.add_argument("--hard-negative-start-epoch", type=int, default=3)
    return parser.parse_args()


def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def read_csv(path: str) -> Iterable[Dict[str, str]]:
    with open(path, newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            yield row


def as_float(value: str) -> float:
    if value is None or value == "":
        return 0.0
    return float(value)


def as_int(value: str) -> int:
    if value is None or value == "":
        return 0
    return int(float(value))


def log1p_amount(value: str) -> float:
    return math.log1p(max(0.0, as_float(value)))


def stable_categories(values: Iterable[str], max_items: int) -> List[str]:
    counter = Counter(v or "UNKNOWN" for v in values)
    return [item for item, _ in counter.most_common(max_items)]


def one_hot(value: str, categories: List[str]) -> List[float]:
    value = value or "UNKNOWN"
    return [1.0 if value == category else 0.0 for category in categories]


def standardize(features: torch.Tensor) -> torch.Tensor:
    mean = features.mean(dim=0, keepdim=True)
    std = features.std(dim=0, keepdim=True).clamp_min(1e-6)
    return (features - mean) / std


def fit_standardizer(features: torch.Tensor, index: torch.Tensor = None) -> Tuple[torch.Tensor, torch.Tensor]:
    scoped = features if index is None or index.numel() == 0 else features[index]
    mean = scoped.mean(dim=0, keepdim=True)
    std = scoped.std(dim=0, keepdim=True).clamp_min(1e-6)
    return mean, std


def apply_standardizer(features: torch.Tensor, mean: torch.Tensor, std: torch.Tensor) -> torch.Tensor:
    return (features - mean) / std


def tensor_stats_to_json(mean: torch.Tensor, std: torch.Tensor) -> Dict[str, List[float]]:
    return {
        "mean": [float(value) for value in mean.squeeze(0).tolist()],
        "std": [float(value) for value in std.squeeze(0).tolist()],
    }


def tensor_stats_from_json(payload: Dict[str, List[float]]) -> Tuple[torch.Tensor, torch.Tensor]:
    mean = torch.tensor(payload["mean"], dtype=torch.float32).view(1, -1)
    std = torch.tensor(payload["std"], dtype=torch.float32).view(1, -1).clamp_min(1e-6)
    return mean, std


def load_v2_edge_features(data_dir: str) -> Dict[int, Dict[str, str]]:
    path = os.path.join(data_dir, "edge_features_v2.csv")
    if not os.path.exists(path):
        return {}
    return {as_int(row["edge_id"]): row for row in read_csv(path)}


def load_temporal_edge_features(path: str) -> Tuple[Dict[int, List[float]], List[str]]:
    if not path:
        raise ValueError("feature_mode=temporal_v1 requires --temporal-feature-file")
    if not os.path.exists(path):
        raise FileNotFoundError(path)
    rows = {}
    feature_columns: List[str] = []
    with open(path, newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        feature_columns = [column for column in (reader.fieldnames or []) if column.startswith("f")]
        if not feature_columns:
            raise ValueError("temporal feature file has no fNNN feature columns")
        for row in reader:
            model_index = as_int(row.get("model_index", ""))
            rows[model_index] = [as_float(row.get(column, "0")) for column in feature_columns]
    return rows, feature_columns


def optional_float(row: Dict[str, str], key: str, default: float = 0.0) -> float:
    return as_float(row.get(key, str(default)))


def feedback_label(row: Dict[str, str], original_label: float) -> float:
    value = row.get("feedback_label")
    if value is None or value == "":
        return original_label
    return float(as_int(value))


def feedback_weight(row: Dict[str, str]) -> float:
    value = row.get("feedback_weight")
    if value is None or value == "":
        return 1.0
    return max(0.0, float(value))


def parse_event_order(row: Dict[str, str], fallback_index: int) -> float:
    value = row.get("event_time", "")
    if value:
        text = value.strip()
        for fmt in ("%Y-%m-%d %H:%M:%S.%f", "%Y-%m-%d %H:%M:%S"):
            try:
                return datetime.strptime(text, fmt).timestamp()
            except ValueError:
                pass
    source_row_no = row.get("source_row_no")
    if source_row_no:
        try:
            return float(source_row_no)
        except ValueError:
            pass
    return float(fallback_index)


def historical_edge_features(edge_rows: List[Dict[str, str]]) -> Dict[int, List[float]]:
    ordered = sorted(enumerate(edge_rows), key=lambda item: (parse_event_order(item[1], item[0]), item[0]))
    node_stats: Dict[int, Dict[str, float]] = {}
    pair_stats: Dict[Tuple[int, int], Dict[str, float]] = {}
    features: Dict[int, List[float]] = {}

    def stats_for(node_id: int) -> Dict[str, float]:
        if node_id not in node_stats:
            node_stats[node_id] = {
                "in_count": 0.0,
                "out_count": 0.0,
                "in_amount": 0.0,
                "out_amount": 0.0,
                "last_in_time": 0.0,
                "last_out_time": 0.0,
            }
        return node_stats[node_id]

    def pair_for(src_id: int, dst_id: int) -> Dict[str, float]:
        key = (src_id, dst_id)
        if key not in pair_stats:
            pair_stats[key] = {"count": 0.0, "amount": 0.0, "last_time": 0.0}
        return pair_stats[key]

    for original_index, row in ordered:
        src_id = as_int(row["from_node_id"])
        dst_id = as_int(row["to_node_id"])
        amount = max(0.0, as_float(row.get("amount", "0")))
        current_time = parse_event_order(row, original_index)
        src_stats = stats_for(src_id)
        dst_stats = stats_for(dst_id)
        pair = pair_for(src_id, dst_id)
        src_total = src_stats["in_amount"] + src_stats["out_amount"]
        dst_total = dst_stats["in_amount"] + dst_stats["out_amount"]
        src_last_time = max(src_stats["last_in_time"], src_stats["last_out_time"])
        dst_last_time = max(dst_stats["last_in_time"], dst_stats["last_out_time"])

        features[original_index] = [
            math.log1p(src_stats["in_count"]),
            math.log1p(src_stats["out_count"]),
            math.log1p(dst_stats["in_count"]),
            math.log1p(dst_stats["out_count"]),
            math.log1p(src_stats["in_amount"]),
            math.log1p(src_stats["out_amount"]),
            math.log1p(dst_stats["in_amount"]),
            math.log1p(dst_stats["out_amount"]),
            math.log1p(pair["count"]),
            math.log1p(pair["amount"]),
            amount / max(1.0, src_total),
            amount / max(1.0, dst_total),
            0.0 if src_last_time <= 0 else math.log1p(max(0.0, current_time - src_last_time) / 60.0),
            0.0 if dst_last_time <= 0 else math.log1p(max(0.0, current_time - dst_last_time) / 60.0),
            0.0 if pair["last_time"] <= 0 else math.log1p(max(0.0, current_time - pair["last_time"]) / 60.0),
            1.0 if src_id == dst_id else 0.0,
        ]

        src_stats["out_count"] += 1.0
        src_stats["out_amount"] += amount
        src_stats["last_out_time"] = current_time
        dst_stats["in_count"] += 1.0
        dst_stats["in_amount"] += amount
        dst_stats["last_in_time"] = current_time
        pair["count"] += 1.0
        pair["amount"] += amount
        pair["last_time"] = current_time
    return features


def load_graph(data_dir: str, max_edges: int = 0, feature_mode: str = "v1",
               feedback_mode: str = "label", standardize_features: bool = True,
               temporal_feature_file: str = None) -> Tuple[
    torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, Dict
]:
    nodes_path = os.path.join(data_dir, "nodes.csv")
    edges_path = os.path.join(data_dir, "edges.csv")

    node_rows = list(read_csv(nodes_path))
    edge_rows = []
    for row in read_csv(edges_path):
        edge_rows.append(row)
        if max_edges > 0 and len(edge_rows) >= max_edges:
            break

    node_id_to_idx = {as_int(row["node_id"]): idx for idx, row in enumerate(node_rows)}
    node_type_categories = stable_categories((row.get("node_type", "UNKNOWN") for row in node_rows), 8)

    node_features = []
    for row in node_rows:
        fraud_features = []
        if feature_mode == "v1":
            fraud_features = [
                math.log1p(as_float(row.get("fraud_in_degree", "0"))),
                math.log1p(as_float(row.get("fraud_out_degree", "0"))),
            ]
        numeric = []
        if feature_mode in ("v1", "v2"):
            numeric = [
                math.log1p(as_float(row.get("in_degree", "0"))),
                math.log1p(as_float(row.get("out_degree", "0"))),
                log1p_amount(row.get("total_in_amount", "0")),
                log1p_amount(row.get("total_out_amount", "0")),
            ] + fraud_features
        node_features.append(numeric + one_hot(row.get("node_type", "UNKNOWN"), node_type_categories))
    x = torch.tensor(node_features, dtype=torch.float32)
    if standardize_features:
        x = standardize(x)

    edge_type_categories = stable_categories((row.get("edge_type", "UNKNOWN") for row in edge_rows), 16)
    currency_categories = stable_categories((row.get("currency", "UNKNOWN") for row in edge_rows), 8)
    v2_features_by_edge = load_v2_edge_features(data_dir) if feature_mode in ("v2", "v3") else {}
    historical_features = historical_edge_features(edge_rows) if feature_mode == "v3" else {}
    temporal_features_by_index, temporal_feature_columns = ({}, [])
    if feature_mode == "temporal_v1":
        temporal_features_by_index, temporal_feature_columns = load_temporal_edge_features(temporal_feature_file)

    src = []
    dst = []
    edge_features = []
    labels = []
    weights = []
    missing_nodes = 0
    feedback_overrides = 0
    zero_weight_edges = 0
    for row_index, row in enumerate(edge_rows):
        from_id = as_int(row["from_node_id"])
        to_id = as_int(row["to_node_id"])
        if from_id not in node_id_to_idx or to_id not in node_id_to_idx:
            missing_nodes += 1
            continue
        model_index = len(labels)
        src.append(node_id_to_idx[from_id])
        dst.append(node_id_to_idx[to_id])
        source_step = as_float(row.get("source_step", "0"))
        if feature_mode == "temporal_v1":
            if model_index not in temporal_features_by_index:
                raise ValueError(f"temporal feature file is missing model_index={model_index}")
            base_features = list(temporal_features_by_index[model_index])
        else:
            base_features = (
                [
                    log1p_amount(row.get("amount", "0")),
                    math.log1p(max(0.0, source_step)),
                ]
                + one_hot(row.get("edge_type", "UNKNOWN"), edge_type_categories)
                + one_hot(row.get("currency", "UNKNOWN"), currency_categories)
            )
        label = float(as_int(row.get("label_fraud", "0")))
        weight = 1.0
        if feature_mode == "v2":
            extra = v2_features_by_edge.get(as_int(row["edge_id"]), {})
            source_total = optional_float(extra, "source_batch_total_amount")
            target_total = optional_float(extra, "target_batch_total_amount")
            amount = as_float(row.get("amount", "0"))
            v2_numeric = [
                math.log1p(optional_float(extra, "source_in_degree")),
                math.log1p(optional_float(extra, "source_out_degree")),
                math.log1p(optional_float(extra, "target_in_degree")),
                math.log1p(optional_float(extra, "target_out_degree")),
                log1p_amount(extra.get("source_total_in_amount", "0")),
                log1p_amount(extra.get("source_total_out_amount", "0")),
                log1p_amount(extra.get("target_total_in_amount", "0")),
                log1p_amount(extra.get("target_total_out_amount", "0")),
                math.log1p(optional_float(extra, "source_batch_edge_count")),
                math.log1p(optional_float(extra, "target_batch_edge_count")),
                log1p_amount(extra.get("source_batch_avg_amount", "0")),
                log1p_amount(extra.get("target_batch_avg_amount", "0")),
                amount / max(1.0, source_total),
                amount / max(1.0, target_total),
                optional_float(extra, "self_loop"),
                optional_float(extra, "hour_of_day") / 23.0,
                optional_float(extra, "day_of_week") / 7.0,
                optional_float(extra, "is_weekend"),
                optional_float(extra, "is_night"),
            ]
            base_features += v2_numeric
            if feedback_mode == "label":
                adjusted_label = feedback_label(extra, label)
                if adjusted_label != label:
                    feedback_overrides += 1
                label = adjusted_label
                weight = feedback_weight(extra)
            elif feedback_mode == "weight":
                weight = feedback_weight(extra)
            if weight == 0.0:
                zero_weight_edges += 1
        if feature_mode == "v3":
            extra = historical_features.get(row_index, [])
            time_extra = v2_features_by_edge.get(as_int(row["edge_id"]), {}) if v2_features_by_edge else {}
            base_features += extra + [
                optional_float(time_extra, "hour_of_day", 0.0) / 23.0,
                optional_float(time_extra, "day_of_week", 0.0) / 7.0,
                optional_float(time_extra, "is_weekend", 0.0),
                optional_float(time_extra, "is_night", 0.0),
            ]
        edge_features.append(base_features)
        labels.append(label)
        weights.append(weight)

    edge_index = torch.tensor([src, dst], dtype=torch.long)
    edge_attr = torch.tensor(edge_features, dtype=torch.float32)
    if standardize_features:
        edge_attr = standardize(edge_attr)
    y = torch.tensor(labels, dtype=torch.float32)
    sample_weight = torch.tensor(weights, dtype=torch.float32)

    meta = {
        "num_nodes": int(x.size(0)),
        "num_edges": int(edge_index.size(1)),
        "num_positive_edges": int(y.sum().item()),
        "positive_ratio": float(y.mean().item()),
        "node_feature_dim": int(x.size(1)),
        "edge_feature_dim": int(edge_attr.size(1)),
        "node_type_categories": node_type_categories,
        "edge_type_categories": edge_type_categories,
        "currency_categories": currency_categories,
        "missing_nodes": missing_nodes,
        "feature_mode": feature_mode,
        "v2_edge_features_loaded": bool(v2_features_by_edge),
        "historical_features_loaded": bool(historical_features),
        "temporal_features_loaded": bool(temporal_features_by_index),
        "temporal_feature_file": os.path.abspath(temporal_feature_file) if temporal_feature_file else None,
        "temporal_feature_columns": temporal_feature_columns,
        "feedback_mode": feedback_mode,
        "standardize_features_in_loader": standardize_features,
        "feedback_overrides": feedback_overrides,
        "zero_weight_edges": zero_weight_edges,
    }
    return x, edge_index, edge_attr, y, sample_weight, meta


def stratified_split(y: torch.Tensor, seed: int) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    generator = torch.Generator().manual_seed(seed)
    positive = torch.where(y == 1)[0]
    negative = torch.where(y == 0)[0]
    positive = positive[torch.randperm(positive.numel(), generator=generator)]
    negative = negative[torch.randperm(negative.numel(), generator=generator)]

    def split_index(index: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        n = index.numel()
        train_end = int(n * 0.70)
        val_end = int(n * 0.85)
        return index[:train_end], index[train_end:val_end], index[val_end:]

    p_train, p_val, p_test = split_index(positive)
    n_train, n_val, n_test = split_index(negative)

    train = torch.cat([p_train, n_train])
    val = torch.cat([p_val, n_val])
    test = torch.cat([p_test, n_test])
    train = train[torch.randperm(train.numel(), generator=generator)]
    val = val[torch.randperm(val.numel(), generator=generator)]
    test = test[torch.randperm(test.numel(), generator=generator)]
    return train, val, test


def time_split(data_dir: str, max_edges: int, edge_count: int) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    edges_path = os.path.join(data_dir, "edges.csv")
    order_values = []
    for index, row in enumerate(read_csv(edges_path)):
        if max_edges > 0 and index >= max_edges:
            break
        order_values.append((parse_event_order(row, index), index))
    if len(order_values) != edge_count:
        order_values = order_values[:edge_count]
    order = torch.tensor([idx for _, idx in sorted(order_values)], dtype=torch.long)
    n = order.numel()
    train_end = int(n * 0.70)
    val_end = int(n * 0.85)
    return order[:train_end], order[train_end:val_end], order[val_end:]


def external_split(split_file: str, edge_count: int) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, Dict]:
    split_ids = {"train": [], "val": [], "test": []}
    with open(split_file, newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        required = {"model_index", "split"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"split file missing required columns: {sorted(missing)}")
        for row in reader:
            split = row.get("split", "")
            if split not in split_ids:
                continue
            model_index = as_int(row.get("model_index", ""))
            if 0 <= model_index < edge_count:
                split_ids[split].append(model_index)

    tensors = {
        split: torch.tensor(sorted(set(values)), dtype=torch.long)
        for split, values in split_ids.items()
    }
    seen = set()
    duplicates = 0
    for values in split_ids.values():
        for model_index in values:
            if model_index in seen:
                duplicates += 1
            seen.add(model_index)
    missing_count = edge_count - len(seen)
    if duplicates:
        raise ValueError(f"split file has duplicate model_index assignments: {duplicates}")
    if missing_count:
        raise ValueError(f"split file does not assign every loaded edge. missing={missing_count}, edge_count={edge_count}")
    if any(tensor.numel() == 0 for tensor in tensors.values()):
        raise ValueError("split file must contain non-empty train, val, and test assignments")

    meta = {
        "split_file": os.path.abspath(split_file),
        "split_file_train_edges": int(tensors["train"].numel()),
        "split_file_val_edges": int(tensors["val"].numel()),
        "split_file_test_edges": int(tensors["test"].numel()),
    }
    return tensors["train"], tensors["val"], tensors["test"], meta


def standardize_by_train_scope(x: torch.Tensor, edge_attr: torch.Tensor, edge_index: torch.Tensor,
                               train_ids: torch.Tensor, scope: str) -> Tuple[torch.Tensor, torch.Tensor, Dict]:
    if scope == "full":
        node_mean, node_std = fit_standardizer(x)
        edge_mean, edge_std = fit_standardizer(edge_attr)
    else:
        train_node_ids = torch.unique(edge_index[:, train_ids].reshape(-1)) if train_ids.numel() > 0 else None
        node_mean, node_std = fit_standardizer(x, train_node_ids)
        edge_mean, edge_std = fit_standardizer(edge_attr, train_ids)
    normalized_x = apply_standardizer(x, node_mean, node_std)
    normalized_edge_attr = apply_standardizer(edge_attr, edge_mean, edge_std)
    stats = {
        "scope": scope,
        "node": tensor_stats_to_json(node_mean, node_std),
        "edge": tensor_stats_to_json(edge_mean, edge_std),
    }
    return normalized_x, normalized_edge_attr, stats


def apply_normalization_from_meta(x: torch.Tensor, edge_attr: torch.Tensor, meta: Dict) -> Tuple[torch.Tensor, torch.Tensor]:
    normalization = meta.get("normalization")
    if not normalization or "node" not in normalization or "edge" not in normalization:
        return standardize(x), standardize(edge_attr)
    node_mean, node_std = tensor_stats_from_json(normalization["node"])
    edge_mean, edge_std = tensor_stats_from_json(normalization["edge"])
    return apply_standardizer(x, node_mean, node_std), apply_standardizer(edge_attr, edge_mean, edge_std)


def build_normalized_adj(edge_index: torch.Tensor, num_nodes: int, device: torch.device) -> torch.Tensor:
    src = edge_index[0]
    dst = edge_index[1]
    all_src = torch.cat([src, dst, torch.arange(num_nodes, dtype=torch.long)])
    all_dst = torch.cat([dst, src, torch.arange(num_nodes, dtype=torch.long)])
    values = torch.ones(all_src.numel(), dtype=torch.float32)
    degree = torch.zeros(num_nodes, dtype=torch.float32)
    degree.scatter_add_(0, all_dst, values)
    norm_values = values / degree[all_dst].clamp_min(1.0)
    indices = torch.stack([all_dst, all_src], dim=0)
    return torch.sparse_coo_tensor(indices, norm_values, (num_nodes, num_nodes)).coalesce().to(device)


def build_directed_adjs(edge_index: torch.Tensor, num_nodes: int, device: torch.device) -> Tuple[torch.Tensor, torch.Tensor]:
    src = edge_index[0]
    dst = edge_index[1]

    def normalize(row: torch.Tensor, col: torch.Tensor) -> torch.Tensor:
        self_nodes = torch.arange(num_nodes, dtype=torch.long)
        row = torch.cat([row, self_nodes])
        col = torch.cat([col, self_nodes])
        values = torch.ones(row.numel(), dtype=torch.float32)
        degree = torch.zeros(num_nodes, dtype=torch.float32)
        degree.scatter_add_(0, row, values)
        norm_values = values / degree[row].clamp_min(1.0)
        indices = torch.stack([row, col], dim=0)
        return torch.sparse_coo_tensor(indices, norm_values, (num_nodes, num_nodes)).coalesce().to(device)

    inbound_adj = normalize(dst, src)
    outbound_adj = normalize(src, dst)
    return inbound_adj, outbound_adj


def build_model_adj(edge_index: torch.Tensor, num_nodes: int, device: torch.device, architecture: str):
    if architecture == "directed-edge-sage":
        return build_directed_adjs(edge_index, num_nodes, device)
    return build_normalized_adj(edge_index, num_nodes, device)


def adjacency_edges(edge_index: torch.Tensor, train_ids: torch.Tensor, scope: str) -> torch.Tensor:
    if scope == "train":
        return edge_index[:, train_ids.cpu()]
    return edge_index


class GraphSageLayer(nn.Module):
    def __init__(self, in_dim: int, out_dim: int):
        super().__init__()
        self.linear = nn.Linear(in_dim * 2, out_dim)

    def forward(self, x: torch.Tensor, adj: torch.Tensor) -> torch.Tensor:
        neigh = torch.sparse.mm(adj, x)
        return self.linear(torch.cat([x, neigh], dim=-1))


class EdgeGraphSage(nn.Module):
    def __init__(self, node_in: int, edge_in: int, hidden: int, dropout: float):
        super().__init__()
        self.sage1 = GraphSageLayer(node_in, hidden)
        self.sage2 = GraphSageLayer(hidden, hidden)
        self.dropout = nn.Dropout(dropout)
        self.edge_mlp = nn.Sequential(
            nn.Linear(hidden * 4 + edge_in, hidden),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden, 1),
        )

    def encode(self, x: torch.Tensor, adj: torch.Tensor) -> torch.Tensor:
        h = F.relu(self.sage1(x, adj))
        h = self.dropout(h)
        h = F.relu(self.sage2(h, adj))
        return h

    def classify_edges(self, h: torch.Tensor, edge_index: torch.Tensor, edge_attr: torch.Tensor,
                       edge_ids: torch.Tensor) -> torch.Tensor:
        src = edge_index[0, edge_ids]
        dst = edge_index[1, edge_ids]
        hs = h[src]
        hd = h[dst]
        ea = edge_attr[edge_ids]
        features = torch.cat([hs, hd, torch.abs(hs - hd), hs * hd, ea], dim=-1)
        return self.edge_mlp(features).squeeze(-1)


class DirectedGraphSageLayer(nn.Module):
    def __init__(self, in_dim: int, out_dim: int):
        super().__init__()
        self.linear = nn.Linear(in_dim * 3, out_dim)

    def forward(self, x: torch.Tensor, adj: Tuple[torch.Tensor, torch.Tensor]) -> torch.Tensor:
        inbound_adj, outbound_adj = adj
        inbound = torch.sparse.mm(inbound_adj, x)
        outbound = torch.sparse.mm(outbound_adj, x)
        return self.linear(torch.cat([x, inbound, outbound], dim=-1))


class DirectedEdgeGraphSage(nn.Module):
    def __init__(self, node_in: int, edge_in: int, hidden: int, dropout: float):
        super().__init__()
        self.sage1 = DirectedGraphSageLayer(node_in, hidden)
        self.sage2 = DirectedGraphSageLayer(hidden, hidden)
        self.dropout = nn.Dropout(dropout)
        self.edge_encoder = nn.Sequential(
            nn.Linear(edge_in, hidden),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden, hidden),
            nn.ReLU(),
        )
        self.edge_update = nn.Sequential(
            nn.Linear(hidden * 5, hidden),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden, hidden),
            nn.ReLU(),
        )
        self.edge_head = nn.Linear(hidden, 1)

    def encode(self, x: torch.Tensor, adj: Tuple[torch.Tensor, torch.Tensor]) -> torch.Tensor:
        h = F.relu(self.sage1(x, adj))
        h = self.dropout(h)
        h = F.relu(self.sage2(h, adj))
        return h

    def classify_edges(self, h: torch.Tensor, edge_index: torch.Tensor, edge_attr: torch.Tensor,
                       edge_ids: torch.Tensor) -> torch.Tensor:
        src = edge_index[0, edge_ids]
        dst = edge_index[1, edge_ids]
        hs = h[src]
        hd = h[dst]
        edge_state = self.edge_encoder(edge_attr[edge_ids])
        updated = self.edge_update(torch.cat([hs, hd, torch.abs(hs - hd), hs * hd, edge_state], dim=-1))
        return self.edge_head(updated).squeeze(-1)


def create_model(architecture: str, node_in: int, edge_in: int, hidden: int, dropout: float) -> nn.Module:
    if architecture == "directed-edge-sage":
        return DirectedEdgeGraphSage(node_in, edge_in, hidden, dropout)
    return EdgeGraphSage(node_in, edge_in, hidden, dropout)


@torch.no_grad()
def binary_auc(scores: torch.Tensor, labels: torch.Tensor) -> float:
    labels = labels.float()
    pos = labels.sum().item()
    neg = labels.numel() - pos
    if pos == 0 or neg == 0:
        return float("nan")
    order = torch.argsort(scores)
    ranks = torch.empty_like(order, dtype=torch.float32)
    ranks[order] = torch.arange(1, labels.numel() + 1, device=scores.device, dtype=torch.float32)
    pos_rank_sum = ranks[labels == 1].sum().item()
    return (pos_rank_sum - pos * (pos + 1) / 2.0) / (pos * neg)


@torch.no_grad()
def average_precision(scores: torch.Tensor, labels: torch.Tensor) -> float:
    labels = labels.float()
    pos = labels.sum().item()
    if pos == 0:
        return float("nan")
    order = torch.argsort(scores, descending=True)
    sorted_labels = labels[order]
    tp = torch.cumsum(sorted_labels, dim=0)
    rank = torch.arange(1, sorted_labels.numel() + 1, device=scores.device, dtype=torch.float32)
    precision = tp / rank
    return (precision * sorted_labels).sum().item() / pos


@torch.no_grad()
def evaluate(model: nn.Module, x: torch.Tensor, adj, edge_index: torch.Tensor,
             edge_attr: torch.Tensor, y: torch.Tensor, edge_ids: torch.Tensor,
             batch_size: int) -> Dict[str, float]:
    model.eval()
    if edge_ids.numel() == 0:
        return {
            "loss": float("nan"),
            "auc": float("nan"),
            "ap": float("nan"),
            "precision": 0.0,
            "recall": 0.0,
            "f1": 0.0,
            "recall_at_5x_pos": 0.0,
            "best_threshold": 0.5,
            "best_precision": 0.0,
            "best_recall": 0.0,
            "best_f1": 0.0,
            "tp": 0,
            "fp": 0,
            "fn": 0,
            "tn": 0,
            "positive_edges": 0,
            "total_edges": 0,
        }
    h = model.encode(x, adj)
    logits_parts = []
    for start in range(0, edge_ids.numel(), batch_size):
        ids = edge_ids[start:start + batch_size]
        logits_parts.append(model.classify_edges(h, edge_index, edge_attr, ids))
    logits = torch.cat(logits_parts)
    labels = y[edge_ids]
    probs = torch.sigmoid(logits)
    preds = (probs >= 0.5).float()
    tp = ((preds == 1) & (labels == 1)).sum().item()
    fp = ((preds == 1) & (labels == 0)).sum().item()
    fn = ((preds == 0) & (labels == 1)).sum().item()
    tn = ((preds == 0) & (labels == 0)).sum().item()
    precision = tp / max(1, tp + fp)
    recall = tp / max(1, tp + fn)
    f1 = 2 * precision * recall / max(1e-12, precision + recall)

    top_k = min(max(1, int(labels.sum().item() * 5)), labels.numel())
    top_idx = torch.topk(probs, k=top_k).indices
    recall_at_top = labels[top_idx].sum().item() / max(1.0, labels.sum().item())

    order = torch.argsort(probs, descending=True)
    sorted_probs = probs[order]
    sorted_labels = labels[order]
    tp_curve = torch.cumsum(sorted_labels, dim=0)
    rank = torch.arange(1, sorted_labels.numel() + 1, device=probs.device, dtype=torch.float32)
    precision_curve = tp_curve / rank
    recall_curve = tp_curve / max(1.0, labels.sum().item())
    f1_curve = 2 * precision_curve * recall_curve / (precision_curve + recall_curve).clamp_min(1e-12)
    best_idx = int(torch.argmax(f1_curve).item())
    best_threshold = float(sorted_probs[best_idx].item())
    best_precision = float(precision_curve[best_idx].item())
    best_recall = float(recall_curve[best_idx].item())
    best_f1 = float(f1_curve[best_idx].item())

    return {
        "loss": F.binary_cross_entropy_with_logits(logits, labels).item(),
        "auc": binary_auc(probs, labels),
        "ap": average_precision(probs, labels),
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "recall_at_5x_pos": recall_at_top,
        "best_threshold": best_threshold,
        "best_precision": best_precision,
        "best_recall": best_recall,
        "best_f1": best_f1,
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "tn": tn,
        "positive_edges": int(labels.sum().item()),
        "total_edges": int(labels.numel()),
    }


def training_loss(logits: torch.Tensor, labels: torch.Tensor, sample_weight: torch.Tensor,
                  pos_weight: torch.Tensor, loss_type: str, focal_gamma: float) -> torch.Tensor:
    bce = F.binary_cross_entropy_with_logits(logits, labels, pos_weight=pos_weight, reduction="none")
    if loss_type == "focal":
        probs = torch.sigmoid(logits)
        p_t = probs * labels + (1.0 - probs) * (1.0 - labels)
        bce = bce * torch.pow((1.0 - p_t).clamp_min(1e-6), focal_gamma)
    weighted = bce * sample_weight
    return weighted.sum() / sample_weight.sum().clamp_min(1.0)


def hard_negative_sample_weight(logits: torch.Tensor, labels: torch.Tensor, base_weight: torch.Tensor,
                                epoch: int, ratio: float, hard_weight: float,
                                start_epoch: int) -> Tuple[torch.Tensor, int]:
    if ratio <= 0.0 or hard_weight <= 1.0 or epoch < start_epoch:
        return base_weight, 0
    positive_count = int((labels == 1).sum().item())
    negative_ids = torch.where(labels == 0)[0]
    hard_count = min(negative_ids.numel(), max(1, int(positive_count * ratio)))
    if positive_count <= 0 or hard_count <= 0:
        return base_weight, 0
    negative_probs = torch.sigmoid(logits.detach()[negative_ids])
    hard_local = torch.topk(negative_probs, k=hard_count).indices
    hard_ids = negative_ids[hard_local]
    effective_weight = base_weight.clone()
    effective_weight[hard_ids] = effective_weight[hard_ids] * hard_weight
    return effective_weight, int(hard_count)


def train(args: argparse.Namespace) -> Dict:
    set_seed(args.seed)
    os.makedirs(args.output_dir, exist_ok=True)
    device = torch.device(args.device)

    standardize_in_loader = args.standardize_scope == "full" and args.split_mode == "stratified" and not args.split_file
    x, edge_index, edge_attr, y, sample_weight, meta = load_graph(
        args.data_dir, args.max_edges, args.feature_mode, args.feedback_mode, standardize_in_loader,
        args.temporal_feature_file)
    split_meta = {}
    if args.split_file:
        train_ids, val_ids, test_ids, split_meta = external_split(args.split_file, edge_index.size(1))
        effective_split_mode = "external_temporal"
    elif args.split_mode == "time":
        train_ids, val_ids, test_ids = time_split(args.data_dir, args.max_edges, edge_index.size(1))
        effective_split_mode = "time"
    else:
        train_ids, val_ids, test_ids = stratified_split(y, args.seed)
        effective_split_mode = "stratified"
    if not standardize_in_loader:
        x, edge_attr, normalization_stats = standardize_by_train_scope(
            x, edge_attr, edge_index, train_ids, args.standardize_scope)
        meta["normalization"] = normalization_stats
    else:
        meta["normalization"] = {"scope": "loader_full"}
    meta.update({
        "train_edges": int(train_ids.numel()),
        "val_edges": int(val_ids.numel()),
        "test_edges": int(test_ids.numel()),
        "train_positive_edges": int(y[train_ids].sum().item()),
        "val_positive_edges": int(y[val_ids].sum().item()),
        "test_positive_edges": int(y[test_ids].sum().item()),
        "device": str(device),
        "epochs": args.epochs,
        "hidden_dim": args.hidden_dim,
        "batch_size": args.batch_size,
        "loss": args.loss,
        "focal_gamma": args.focal_gamma,
        "architecture": args.architecture,
        "split_mode": args.split_mode,
        "effective_split_mode": effective_split_mode,
        "split_file": os.path.abspath(args.split_file) if args.split_file else None,
        "standardize_scope": args.standardize_scope,
        "adjacency_scope": args.adjacency_scope,
        "hard_negative_ratio": args.hard_negative_ratio,
        "hard_negative_weight": args.hard_negative_weight,
        "hard_negative_start_epoch": args.hard_negative_start_epoch,
    })
    meta.update(split_meta)
    print(json.dumps(meta, indent=2, ensure_ascii=False))

    x = x.to(device)
    edge_index = edge_index.to(device)
    edge_attr = edge_attr.to(device)
    y = y.to(device)
    sample_weight = sample_weight.to(device)
    train_ids = train_ids.to(device)
    val_ids = val_ids.to(device)
    test_ids = test_ids.to(device)
    adj_edge_index = adjacency_edges(edge_index.cpu(), train_ids.cpu(), args.adjacency_scope)
    adj = build_model_adj(adj_edge_index, x.size(0), device, args.architecture)

    model = create_model(args.architecture, x.size(1), edge_attr.size(1), args.hidden_dim, args.dropout).to(device)
    positives = y[train_ids].sum().item()
    negatives = train_ids.numel() - positives
    pos_weight = torch.tensor([negatives / max(1.0, positives)], device=device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    best_val_ap = -1.0
    best_payload = None
    history = []

    for epoch in range(1, args.epochs + 1):
        start_time = time.time()
        model.train()
        h = model.encode(x, adj)
        logits = model.classify_edges(h, edge_index, edge_attr, train_ids)
        effective_sample_weight, hard_negative_count = hard_negative_sample_weight(
            logits, y[train_ids], sample_weight[train_ids], epoch, args.hard_negative_ratio,
            args.hard_negative_weight, args.hard_negative_start_epoch)
        loss = training_loss(logits, y[train_ids], effective_sample_weight,
                             pos_weight, args.loss, args.focal_gamma)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()

        train_loss = loss.item()
        val_metrics = evaluate(model, x, adj, edge_index, edge_attr, y, val_ids, args.batch_size)
        epoch_record = {
            "epoch": epoch,
            "train_loss": train_loss,
            "seconds": time.time() - start_time,
            "hard_negative_count": hard_negative_count,
        }
        epoch_record.update({"val_" + key: value for key, value in val_metrics.items()})
        history.append(epoch_record)
        print(json.dumps(epoch_record, ensure_ascii=False))

        if best_payload is None or (not math.isnan(val_metrics["ap"]) and val_metrics["ap"] > best_val_ap):
            best_val_ap = val_metrics["ap"]
            best_payload = {
                "model_state": {key: value.detach().cpu() for key, value in model.state_dict().items()},
                "meta": meta,
                "epoch": epoch,
                "val_metrics": val_metrics,
            }

    if best_payload is not None:
        model.load_state_dict(best_payload["model_state"])
    test_metrics = evaluate(model, x, adj, edge_index, edge_attr, y, test_ids, args.batch_size)
    result = {
        "meta": meta,
        "best_epoch": best_payload["epoch"] if best_payload else None,
        "best_val_metrics": best_payload["val_metrics"] if best_payload else None,
        "test_metrics": test_metrics,
        "history": history,
    }

    with open(os.path.join(args.output_dir, "metrics.json"), "w", encoding="utf-8") as handle:
        json.dump(result, handle, indent=2, ensure_ascii=False)
    if best_payload is not None:
        torch.save(best_payload, os.path.join(args.output_dir, "best_model.pt"))
    return result


def main() -> None:
    args = parse_args()
    result = train(args)
    print("Final test metrics:")
    print(json.dumps(result["test_metrics"], indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
